services:
  # Spring Boot Application
  - type: web
    name: forts-of-swarajya
    env: docker
    dockerfilePath: ./Dockerfile
    region: oregon
    plan: free
    healthCheckPath: /health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PORT
        value: 8080
      # PostgreSQL Credentials & Connection
      - key: PGHOST
        fromDatabase:
          name: forts-db
          property: host
      - key: PGPORT
        fromDatabase:
          name: forts-db
          property: port
      - key: PGDATABASE
        fromDatabase:
          name: forts-db
          property: database
      - key: PGUSER
        fromDatabase:
          name: forts-db
          property: user
      - key: PGPASSWORD
        fromDatabase:
          name: forts-db
          property: password

databases:
  - name: forts-db
    databaseName: forts_db
    user: fortuser
    region: oregon
    plan: free
